import type {
  BillingRecord,
  InsuranceRecord,
  PaymentRecord,
} from "@/lib/types";

export const mockBillingRecords: BillingRecord[] = [
  {
    id: "1",
    patientId: "1",
    patientName: "Ram",
    serviceCode: "99213",
    serviceDescription: "Office Visit - Established Patient",
    amount: "150.00",
    serviceDate: "2024-01-15",
    status: "paid",
    insuranceProvider: "Blue Cross Blue Shield",
    claimNumber: "CLM001",
  },
  {
    id: "2",
    patientId: "2",
    patientName: "Sarah",
    serviceCode: "99214",
    serviceDescription: "Office Visit - Comprehensive",
    amount: "225.00",
    serviceDate: "2024-01-14",
    status: "pending",
    insuranceProvider: "Aetna",
    claimNumber: "CLM002",
  },
  {
    id: "3",
    patientId: "3",
    patientName: "Jaan",
    serviceCode: "80053",
    serviceDescription: "Comprehensive Metabolic Panel",
    amount: "85.00",
    serviceDate: "2024-01-13",
    status: "submitted",
    insuranceProvider: "United Healthcare",
    claimNumber: "CLM003",
  },
];

export const mockInsuranceRecords: InsuranceRecord[] = [
  {
    id: "1",
    patientId: "1",
    patientName: "Ram",
    dateOfBirth: "1980-05-15",
    insuranceProvider: "Blue Cross Blue Shield",
    policyNumber: "BCBS123456789",
    groupNumber: "GRP001",
    deductible: "500",
    copay: "25",
    status: "active",
    effectiveDate: "2024-01-01",
    expirationDate: "2024-12-31",
  },
  {
    id: "2",
    patientId: "2",
    patientName: "Sarah",
    dateOfBirth: "1975-08-22",
    insuranceProvider: "Aetna",
    policyNumber: "AET987654321",
    groupNumber: "GRP002",
    deductible: "1000",
    copay: "30",
    status: "active",
    effectiveDate: "2024-01-01",
    expirationDate: "2024-12-31",
  },
  {
    id: "3",
    patientId: "3",
    patientName: "Jaan",
    dateOfBirth: "1990-03-10",
    insuranceProvider: "United Healthcare",
    policyNumber: "UHC456789123",
    groupNumber: "GRP003",
    deductible: "750",
    copay: "20",
    status: "pending",
    effectiveDate: "2024-02-01",
    expirationDate: "2025-01-31",
  },
];

export const mockPaymentHistory: PaymentRecord[] = [
  {
    id: "1",
    patientId: "1",
    patientName: "Ram",
    amount: "150.00",
    paymentMethod: "credit_card",
    paymentDate: "2024-01-15",
    status: "completed",
    transactionId: "TXN001",
    billingRecordId: "1",
  },
  {
    id: "2",
    patientId: "2",
    patientName: "Sarah",
    amount: "225.00",
    paymentMethod: "insurance",
    paymentDate: "2024-01-14",
    status: "pending",
    transactionId: "TXN002",
    billingRecordId: "2",
  },
  {
    id: "3",
    patientId: "3",
    patientName: "Jaan",
    amount: "85.00",
    paymentMethod: "cash",
    paymentDate: "2024-01-13",
    status: "completed",
    transactionId: "TXN003",
    billingRecordId: "3",
  },
];
